version: '3.9'

services:
  backend:
    image: python:3.11-slim
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    env_file:
      - backend/.env
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  ai_gateway:
    image: python:3.11-slim
    working_dir: /app/ai_gateway
    depends_on:
      - backend
    volumes:
      - ./ai_gateway:/app/ai_gateway
    env_file:
      - ai_gateway/.env
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8010"
    ports:
      - "8010:8010"

  webapp:
    image: node:20-alpine
    working_dir: /app/webapp
    depends_on:
      - backend
      - ai_gateway
    volumes:
      - ./webapp:/app/webapp
    env_file:
      - webapp/.env
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
