[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = "(app/(main|auth)\\.py|(^|/)tests/|app/tests/)"

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  ".venv",
  "alembic/versions",
]
extend-exclude = [
  "app/main.py",
  "app/auth.py",
  "tests",
  "app/tests",
]

[tool.ruff.lint]
select = [
  "E",
  "F",
  "B",
  "I",
]
ignore = [
  "E501",
  "B008",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
