[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  ".venv",
  "alembic/versions",
]

[tool.ruff.lint]
select = [
  "E",
  "F",
  "B",
  "I",
]
ignore = [
  "E501",
  "B008",
]

[tool.ruff.lint.per-file-ignores]
"app/main.py" = ["E402"]  # Module initialization requires specific import order
"tests/test_environment.py" = ["E402"]  # sys.path modification before imports

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
addopts = "--cov=app.api.procedures --cov=app.api.runs --cov=app.services.procedures --cov=app.services.procedure_runs --cov-report=term-missing --cov-report=xml --cov-fail-under=80"
testpaths = ["tests"]
filterwarnings = [
  "error::DeprecationWarning",
  "error::PendingDeprecationWarning",
]
markers = [
  "migrations: Tests that validate Alembic migrations against SQLAlchemy models.",
]

[tool.coverage.run]
source = ["app/services"]
omit = [
  "*/app/services/__init__.py",
  "*/app/services/audit.py",
  "*/app/services/procedures.py",
  "*/app/services/procedures/__init__.py",
  "*/app/services/procedures/cache.py",
  "*/app/services/procedures/exceptions.py",
  "*/app/services/procedures/service.py",
  "*/app/services/webrtc.py",
]

[tool.coverage.report]
include = [
  "*/app/services/procedure_runs.py",
  "*/app/services/procedures/*",
]
