[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  ".venv",
  "alembic/versions",
]

[tool.ruff.lint]
select = [
  "E",
  "F",
  "B",
  "I",
]
ignore = [
  "E501",
  "B008",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
addopts = "--cov=app --cov-report=term-missing --cov-report=xml --cov-fail-under=75"
testpaths = ["tests"]
filterwarnings = [
  "error::DeprecationWarning",
  "error::PendingDeprecationWarning",
]

[tool.coverage.run]
source = ["app"]

[tool.coverage.report]
include = [
  "app/api/webrtc.py",
  "app/services/webrtc.py",
  "app/main.py",
]
