"""normalize procedural schema

Revision ID: 0f9a441a8cda
Revises: b7e4d2f9c8a1
Create Date: 2025-10-14 10:15:36.016757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0f9a441a8cda'
down_revision: Union[str, Sequence[str], None] = 'b7e4d2f9c8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['procedure_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'name', name='uq_procedure_slot_name')
    )
    op.create_table('procedure_step_checklist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['procedure_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'key', name='uq_procedure_step_checklist_key')
    )
    op.create_table('procedure_run_checklist_item_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('checklist_item_id', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['procedure_step_checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['procedure_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'checklist_item_id', name='uq_procedure_run_checklist_item_state')
    )
    op.create_table('procedure_run_slot_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['procedure_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['procedure_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'slot_id', name='uq_procedure_run_slot_value')
    )
    op.drop_column('procedure_steps', 'checklists')
    op.drop_column('procedure_steps', 'slots')
    # The existing WebRTC indexes are intentionally preserved.  They are managed
    # by previous migrations and are unrelated to this schema change, so avoid
    # dropping them during the upgrade.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Matching the upgrade, the WebRTC indexes remain untouched by this
    # migration.  They continue to be provided by earlier revisions.
    op.add_column('procedure_steps', sa.Column('slots', sqlite.JSON(), nullable=False))
    op.add_column('procedure_steps', sa.Column('checklists', sqlite.JSON(), nullable=False))
    op.drop_table('procedure_run_slot_values')
    op.drop_table('procedure_run_checklist_item_states')
    op.drop_table('procedure_step_checklist_items')
    op.drop_table('procedure_slots')
    # ### end Alembic commands ###
